language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: libgit2
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    update: true
    packages: libgit2-dev
    sources:
      - sourceline: 'ppa:opencpu/libgit2'

notifications:
  email:
    on_success: change
    on_failure: change
